Github/CHANGELOG.md
Github/manifest.json
Github/trigger_pull_audit_logs.json

remove useless parameter from the trigger configuration

Github: remove useless parameter from the trigger configuration

---

AWS/aws/s3/queued.py
AWS/aws/sqs/trigger_sqs_messages.py
AWS/manifest.json
AWS/tests/s3/test_logs_trigger.py
AWS/tests/sqs/test_sqs_messages_trigger.py

Fix for AWS non json incoming events 
> sekoia_automation.module - CRITICAL - unexpected character: line 1 column 1 (char 0)

fix for non json events

---

Darktrace/CHANGELOG.md
Darktrace/manifest.json

- Add CHANGELOG.md with the first entry
- Fix the manifest with the slug

Darktrace: some fixes

---

Trellix/CHANGELOG.md
Trellix/manifest.json
Trellix/trigger_trellix_epo.json

Trellix: Update manifests

---

Sophos/manifest.json
Sophos/sophos_module/trigger_sophos_xdr_query.py

Hi @squioc, 
i have notice that the problem is coming from date format. the query doesn't support this format for example '2023-07-17T09:35:38.986+00:00' or this '2023-07-17T09:35:38.986+00:00Z' instead this one is supported '2023-07-17T09:35:38Z'

Change the date format in the from part of the query

---

Sophos/manifest.json
Sophos/sophos_module/trigger_sophos_xdr_query.py
Sophos/tests/test_sophos_xdr_query.py
Sophos/trigger_sophos_xdr_query.json

- Fix the case where the query failed with None in query_id

Change logic of code in case there's no events

---

Sophos/manifest.json
Sophos/sophos_module/trigger_sophos_xdr_query.py

Add time log

---

Sophos/CHANGELOG.md
Sophos/manifest.json
Sophos/sophos_module/trigger_sophos_edr_events.py

Change the way to handle exceptions in the EDR connector

Sophos: Change the way to handle exceptions in the EDR connector

---

Cybereason/CHANGELOG.md
Cybereason/cybereason_modules/connector_pull_events.py
Cybereason/manifest.json

Revert the last modification on GroupIds

Cybereason: fix GroupIds

---

Google/google_module/google_drive_reports.py
Google/manifest.json

- Fix the bug `no attribute 'is_running'`

Fix the bug no attribute is_running

---

Google/google_module/google_drive_reports.py
Google/manifest.json

- Add intake_server to configuration

Add intake_server to configuration

---

CrowdStrike/CHANGELOG.md
CrowdStrike/aws/sqs.py
CrowdStrike/crowdstrike_telemetry/pull_telemetry_events.py
CrowdStrike/manifest.json
CrowdStrike/tests/aws/test_sqs.py

Set the maximum number of messages to get when reading the SQS queue

CrowdStrike: change the way to fetch messages

---

CrowdStrikeFalcon/CHANGELOG.md
CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
CrowdStrikeFalcon/manifest.json

Catch any exceptions and log them

CrowdStrike: catch any exceptions

---

Cybereason/CHANGELOG.md
Cybereason/cybereason_modules/connector_pull_events.py
Cybereason/manifest.json

Sleep the connector when an exception is raised

Cybereason: wait on error

---

AWS/aws/s3/base.py
AWS/aws/s3/queued.py
AWS/aws/s3/trigger_s3_logs.py
AWS/aws/s3/trigger_s3_parquet.py
AWS/aws/s3/trigger_s3_records.py
AWS/aws/sqs/trigger_sqs_messages.py
AWS/aws/utils.py
AWS/manifest.json
AWS/tests/s3/test_records_trigger.py

https://github.com/SEKOIA-IO/automation-library/issues/346
Here is a context

Add logic based to CloudtrailLogs parser on #346

---

Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/base.py
Sekoia.io/tests/triggers/test_base.py

Improve live URL computation to support several regions.

feat(sekoia.io): Better handling of live url

---

AzureActiveDirectory/azure_ad/base.py
AzureActiveDirectory/manifest.json
AzureActiveDirectory/tests/test_actions.py

- Fix coroutine problem 
- Add secret attribut to password

fix async class and secret field

---

SkyhighSecurity/CHANGELOG.md
SkyhighSecurity/gateway_cloud_services/trigger_skyhigh_security_swg.py
SkyhighSecurity/manifest.json

add the collect queue when recreating the collector

SkyHighSecurity; fix when restarting the collector

---

Tehtris/CHANGELOG.md
Tehtris/manifest.json
Tehtris/tehtris_modules/trigger_tehtris_events.py

Add the response as detail to the log when facing an error with the API

Tehtris: add more details when failing

---

Utils/CHANGELOG.md
Utils/manifest.json
Utils/tests/test_get_current_time.py
Utils/utils/action_get_current_time.py

Fix the return of GetCurrentTime action

Utils: fix GetCurrentTime

---

TheHive/manifest.json
TheHive/thehive/create_alert.py

date in ms for the hive: https://docs.strangebee.com/thehive/api-docs/#operation/Create%20Alert
date in sec for module sekoia get alert

fix issue with alert date sec instead of ms

---

CatoNetwork/manifest.json

main issue : [#49841](https://github.com/SekoiaLab/platform/issues/49841)

update mafifest api_key description

---

WithSecure/action_scan_device_for_malware.json
WithSecure/main.py
WithSecure/tests/test_scan_device_for_malware.py
WithSecure/withsecure/scan_device_for_malware.py

WithSecure : add scan malware action

WithSecure : add scan malware action

---

Darktrace/CHANGELOG.md
Darktrace/darktrace_modules/threat_visualizer_log_trigger.py
Darktrace/manifest.json
Darktrace/tests/test_threat_visualizer_log_trigger.py

Adding historicmodelonly=false to unify the clients logs

add historicmodelonly=false

---

WithSecure/CHANGELOG.md
WithSecure/manifest.json

bump version number and update CHANGELOG.md

WithSecure: bump version number

---

HTTP/manifest.json

Bump version to test the new workflow

chore(HTTP): Bump version

---

Checkpoint/CHANGELOG.md
Checkpoint/client/http_client.py
Checkpoint/manifest.json
Checkpoint/tests/client/test_http_client.py

Convert naive datetimes from events into aware ones

Checkpoint: fix naive datetimes

---

AWS/CHANGELOG.md
AWS/main.py
AWS/manifest.json

Register missing AWS S3 flowlogs

AWS: Register AWS S3 flowlogs

---

Checkpoint/CHANGELOG.md
Checkpoint/connectors/checkpoint_harmony_mobile.py
Checkpoint/main.py
Checkpoint/manifest.json
Checkpoint/tests/connectors/test_checkpoint_harmony_mobile_connector.py
Checkpoint/trigger_checkpoint_harmony_events.json
Checkpoint/trigger_checkpoint_harmony_mobile_events.json

Change the name of the connector to spell the product name out

Checkpoint: fix the name of the connector

---

Azure/CHANGELOG.md
Azure/connectors/trigger_azure_eventhub.py
Azure/manifest.json
Azure/tests/test_azure_eventhub_trigger.py

Handle the situation where the message is a list of records.

Azure: change the way to extract the records from the messages

---

Azure/CHANGELOG.md
Azure/connectors/trigger_azure_eventhub.py
Azure/manifest.json
Azure/tests/test_azure_eventhub_trigger.py

- Handle the way when the message is one event

Azure: Fix the way to handle message

---

HTTP/CHANGELOG.md
HTTP/http_module/request_action.py
HTTP/manifest.json

https://github.com/SekoiaLab/platform/issues/51397

up support 204 with application/json header

---

Tehtris/CHANGELOG.md
Tehtris/manifest.json
Tehtris/tehtris_modules/trigger_tehtris_events.py

- add timeout to HTTP requests in order to avoid blocking requests

Tehtris: add timeout to requests

---

AWS/connector_s3_cloudfront.json
AWS/connector_s3_flowlogs.json
AWS/connector_s3_flowlogs_parquet.json
AWS/connector_s3_logs.json
AWS/connector_s3_records.json
AWS/connector_sqs_messages.json
AWS/manifest.json
Azure/connector_azure_eventhub.json
Azure/manifest.json
CrowdStrikeFalcon/connector_event_stream.json
CrowdStrikeFalcon/manifest.json
Google/connector_google_reports.json
Google/manifest.json
Netskope/connector_pull_events_v2.json
Office365/connector_office365_messagetrace.json
Office365/connector_office365_messagetrace_oauth.json
Office365/manifest.json
Proofpoint/connector_pod_events.json
Proofpoint/connector_tap_events.json
Proofpoint/manifest.json
Sophos/connector_sophos_events.json
Sophos/connector_sophos_xdr_query.json
Sophos/manifest.json
Tehtris/connector_tehtris_events.json
Tehtris/manifest.json

Use the same docker parameter as the trigger

fix(connectors): Fixes connector's docker parameter

---

VadeSecure/CHANGELOG.md
VadeSecure/manifest.json
VadeSecure/trigger_m365_events.json
VadeSecure/vadesecure_modules/models.py

- Increase the default ratelimit
- Declare some parameters missing from the trigger configuration

VadeSecure: some adjustments

---

Google/CHANGELOG.md
Google/google_module/pubsub.py
Google/manifest.json

Fix the way to call the stop method of the super class

Google: fix stop method

---

Fastly/CHANGELOG.md
Fastly/manifest.json
Fastly/trigger_fastly_waf.json

- Add beta flag to the connector
- ~~Move the email and the token parameters to the module configuration~~
- Update the description and the name of the connector

Fastly: some improvements

---

SentinelOne/manifest.json
SentinelOne/sentinelone_module/deep_visibility/query.py

- Change `datetime` into `str` in order to be able to push the results as a JSON

fix(deepvisibility): fix basemmodel

---

CrowdStrikeFalcon/CHANGELOG.md
CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
CrowdStrikeFalcon/manifest.json

Add some logs to see in which line we had the problem and also to avoid printing the exception in the logs section.

Add exceptions to http response

---

AWS/CHANGELOG.md
AWS/connector_s3_cloudfront.json
AWS/connector_s3_flowlogs.json
AWS/connector_s3_flowlogs_parquet.json
AWS/connector_s3_logs.json
AWS/connector_s3_records.json
AWS/connector_sqs_messages.json
AWS/connectors/s3/__init__.py
AWS/manifest.json
AWS/trigger_s3_cloudfront.json
AWS/trigger_s3_flowlogs.json
AWS/trigger_s3_flowlogs_parquet.json
AWS/trigger_s3_logs.json
AWS/trigger_s3_records.json
AWS/trigger_sqs_messages.json

Set the option `delete_consumed_messages` to true by default

AWS: reverse delete consumed messages

---

Azure/CHANGELOG.md
Azure/azure_helpers/io.py
Azure/connectors/pull_azure_blob_data.py
Azure/manifest.json
Azure/tests/connector/test_connector.py

Add support for Gzipped files in the Blob Storage connector

Azure: Improvements on the Blob Storage connector

---

Google/CHANGELOG.md
Google/google_module/google_reports.py
Google/manifest.json
Google/tests/test_google_reports.py

related issue : [51284](https://github.com/SekoiaLab/platform/issues/51284)

change the way to stock timestamp

---

Google/CHANGELOG.md
Google/google_module/google_reports.py
Google/manifest.json

- Skip the log with a none value for nextkey

Add nextkey condition

---

Github/CHANGELOG.md
Github/github_modules/audit_log_trigger.py
Github/github_modules/metrics.py
Github/manifest.json
Github/poetry.lock
Github/pyproject.toml
Github/tests/test_audit_log_trigger.py

- Update `sekoia-automation-sdk` to the latest version (1.12.2) and make use of SDK features to forward events to Sekoia.io.

feat(GitHub): Make use of `AsyncConnector` from automation SDK

---

Azure/CHANGELOG.md
Azure/connectors/azure_blob.py
Azure/manifest.json
Azure/tests/connector/test_azure_blob.py

- Add more logs to forward the progression of the connector
- Create a new method to get the list of blobs and select the most recent ones.

Azure: Change the way to list blob

---

Azure/CHANGELOG.md
Azure/connector_azure_blob_storage_events.json
Azure/connector_azure_network_watcher_collector.json
Azure/connectors/azure_blob.py
Azure/connectors/network_watcher.py
Azure/manifest.json
Azure/trigger_azure_blob_storage_events.json
Azure/trigger_azure_network_watcher_collector.json

Add a pause to the connector when no records were forwarded.

Azure: pause the connector when no records were forwarded

---

WithSecure/CHANGELOG.md
WithSecure/manifest.json
WithSecure/pyproject.toml
WithSecure/tests/client/test_auth.py
WithSecure/withsecure/client/auth.py
WithSecure/withsecure/constants.py

This PR introduces an exponential backoff retry strategy to increase
the resilience of the authentication process against WithSecure API instability

Add exponential backoff retry on WithSecure Auth API 

---

.github/workflows/build-modules.yml
.github/workflows/test_results.yml

Changes:
- Update Codecov to the latest version of the GitHub Actions action to support tokenless uploads for PRs.
- Update `upload-artifacts` to the latest version.

ci: Update some actions in GitHub Actions workflow

---

WithSecure/CHANGELOG.md
WithSecure/manifest.json
WithSecure/poetry.lock
WithSecure/pyproject.toml
WithSecure/tests/test_helpers.py
WithSecure/withsecure/helpers.py
WithSecure/withsecure/security_events_connector.py

- Add a retry strategy when fetching events from the API
- Increase the frequency between calls
- Add the transaction id when logging an HTTP error from the WithSecure Elements API
This PR must be merged after #940

WithSecure: Improve the resiliency of the connector

---

IPInfo/CHANGELOG.md
IPInfo/ipinfo/trigger_fetch_ipinfo_database.py
IPInfo/manifest.json
IPInfo/tests/test_trigger_fetch_ipinfo_database.py

- Set default duration according to manifest
- Set AS name based on its number when empty in the IPInfo file

fix(IPInfo): Minor fixes

---

WithSecure/CHANGELOG.md
WithSecure/manifest.json
WithSecure/tests/test_comment_incident.py
WithSecure/tests/test_isolate_device_from_network_action.py
WithSecure/tests/test_list_detections_for_incident.py
WithSecure/tests/test_release_device_from_network_isolation_action.py
WithSecure/tests/test_scan_device_for_malware.py
WithSecure/withsecure/comment_incident.py
WithSecure/withsecure/isolate_device_from_network_action.py
WithSecure/withsecure/list_detections_for_incident.py
WithSecure/withsecure/release_device_from_network_isolation_action.py
WithSecure/withsecure/scan_device_for_malware.py

- Add result model to all actions

Add result model

---

Office365/CHANGELOG.md
Office365/connector_office365_management_activity_api.json
Office365/manifest.json
Retarus/CHANGELOG.md
Retarus/connector_retarus_events.json
Retarus/manifest.json

Fix the configuration of some connectors for which the intake key parameter was missing

Connectors: fix configuration

---

Sekoia.io/CHANGELOG.md
Sekoia.io/action_delete_rule.json
Sekoia.io/action_disable_rule.json
Sekoia.io/action_enable_rule.json
Sekoia.io/action_get_rule.json
Sekoia.io/action_update_rule.json
Sekoia.io/manifest.json

Updated uuids for the rules actions

Updated uuids

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/trigger_office365_management_activity_api.json

declare Office365 Management API connector as a trigger

Office365: declare Office365 Management API connector as a trigger

---

Mimecast/CHANGELOG.md
Mimecast/manifest.json

- add a slug in the manifest 
- add the CHANGELOG
- apply linter

Mimecast: fix the module

---

Nybble/CHANGELOG.md
Nybble/manifest.json

- Remove the docker parameter from the manifest. It can mislead some tools
- add the CHANGELOG.md file

Nybble: fix manifest

---

Nybble/CHANGELOG.md
Nybble/manifest.json
Nybble/nybble_modules/create_alert.py

quick issue found on 1.0.1, fixing a missed json body

Nybble / fix empty json body in some cases

---

Google/CHANGELOG.md
Google/google_module/google_reports.py
Google/manifest.json
Google/trigger_login_service.json

- I misunderstood the way to fix the login value for login service

Fix conf problem

---

Google/CHANGELOG.md
Google/google_module/timestepper.py
Google/manifest.json
Google/trigger_google_reports.json
Google/trigger_login_service.json

- Change days to hours in timestepper because we got a big delay.

Change days to hours in the timestepper

---

Netskope/CHANGELOG.md
Netskope/manifest.json
Netskope/netskope_modules/connector_pull_events_v2.py
Netskope/tests/test_pull_events_v2_connector.py

Add a user-agent to the Netskope Events connector

Netskope: add user-agent to the connector

---

Google/CHANGELOG.md
Google/google_module/google_reports.py
Google/manifest.json

- Catch some Network exception :
1. BrokenPipeError: [Errno 32] Broken pipe
2. OSError: [Errno 101] Network is unreachable

Catch some network exceptions

---

Sekoia.io/action_get_community.json
Sekoia.io/action_get_entity.json
Sekoia.io/action_get_intake.json
Sekoia.io/main.py
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/operation_center/__init__.py
Sekoia.io/sekoiaio/workspace/__init__.py
Sekoia.io/tests/test_actions_getters.py

Create actions to resolve:
* A community
* An entity
* An intake

feat(sekoiaio): add getters for community, entity and intake

---

Sekoia.io/CHANGELOG.md
Sekoia.io/action_get_event_field_common_values.json
Sekoia.io/action_get_events.json
Sekoia.io/action_list_alerts.json
Sekoia.io/action_list_assets.json
Sekoia.io/manifest.json

Add miminum, maximum and default value for actions with `limit` parameter

Sekoia.io: add bounds and default value for limit parameter

---

Mimecast/CHANGELOG.md
Mimecast/manifest.json
Mimecast/mimecast_modules/connector_mimecast_siem.py
Mimecast/mimecast_modules/logging.py
Mimecast/poetry.lock
Mimecast/pyproject.toml

- Change the way to log some information (and the information that are logged)
- Change the way to log message when no events were forwarded
- Fix the way to compute the event lag (specially, when no events were forwarded)

Mimecast: fix logging

---

Trellix/CHANGELOG.md
Trellix/client/http_client.py
Trellix/connector_trellix_edr.json
Trellix/connector_trellix_epo.json
Trellix/connectors/__init__.py
Trellix/connectors/trellix_edr_connector.py
Trellix/connectors/trellix_epo_connector.py
Trellix/manifest.json
Trellix/tests/connectors/conftest.py
Trellix/tests/connectors/test_trellix_edr_connector.py
Trellix/tests/connectors/test_trellix_epo_connector.py
Trellix/trigger_trellix_edr.json
Trellix/trigger_trellix_epo.json

- add a frequency parameter with a pause in the connectors
- add a daily rate limiter

Trellix: cap the requests over time

---

AWS/CHANGELOG.md
AWS/connector_s3_ocsf.json
AWS/connectors/s3/trigger_s3_parquet.py
AWS/main.py
AWS/manifest.json
AWS/tests/connectors/s3/test_trigger_s3_parquet.py
AWS/trigger_s3_ocsf.json

- Add a generic connector to collect Parquet S3 Object
- Declare a connector for OCSF documents

AWS: add connector for OCSF

---

HarfangLab/CHANGELOG.md
HarfangLab/harfanglab/get_hostnames_by_ip_action.py
HarfangLab/manifest.json

Hello ! 
Sorry, I made a mistake on one of the getter's attributes... My bad
It didn't take the IP as input.
Have a nice day!

resolving error json to params

---

Netskope/CHANGELOG.md
Netskope/manifest.json
Netskope/netskope_modules/connector_pubsub_lite.py
Netskope/netskope_modules/logging.py
Netskope/poetry.lock
Netskope/pyproject.toml
Netskope/tests/test_pubsub_lite.py

Handle the error when the incoming message is not a UTF-8 string.

Netskope: handle when failing to decode the incoming message

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/connectors/metrics.py
AWS/manifest.json
Azure/CHANGELOG.md
Azure/connectors/azure_eventhub.py
Azure/connectors/metrics.py
Azure/manifest.json

- add a metric to monitor the age of the older message seen in a batch
- add a metric to monitor the average age of messages seen in a batch

Azure & AWS: add two new metrics to monitor events lag

---

Sophos/CHANGELOG.md
Sophos/manifest.json
Sophos/sophos_module/client/__init__.py

Adjust the rate-limiter according to the [Sophos documentation](https://developer.sophos.com/intro#rate-limits)

Sophos: Adjust the rate-limiters

---

PaloAltoCortexXDR/CHANGELOG.md
PaloAltoCortexXDR/cortex_module/cortex_edr_connector.py
PaloAltoCortexXDR/cortex_module/helper.py
PaloAltoCortexXDR/manifest.json
PaloAltoCortexXDR/tests/test_cortex_edr.py

Issue : [#152](https://github.com/SekoiaLab/integration/issues/152#event-13727614356)

Update alert_url proprety

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/logging.py
Office365/office365/management_api/office365_client.py
Office365/poetry.lock
Office365/pyproject.toml

To fix https://github.com/SekoiaLab/integration/issues/184 we have to get more details

Office365 - log more details for auth errors

---

SkyhighSecurity/CHANGELOG.md
SkyhighSecurity/gateway_cloud_services/trigger_skyhigh_security_swg.py
SkyhighSecurity/manifest.json
SkyhighSecurity/tests/test_gateway_cloud_services_trigger.py

https://github.com/SekoiaLab/integration/issues/164

SkyHigh - Save last seen timestamp

---

SentinelOne/CHANGELOG.md
SentinelOne/action_update_threat_incident.json
SentinelOne/manifest.json
SentinelOne/sentinelone_module/threats/update_threat_incident.py

Change variable name

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/iocs/create_iocs.py

- Add some logs to the action
- Fix the variable type problem

Fix variable type problem

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/iocs/create_iocs.py
SentinelOne/tests/iocs/test_create_iocs.py

Change type of data sent

---

MicrosoftEntraID/CHANGELOG.md
MicrosoftEntraID/action_get_user_authentication_methods.json
MicrosoftEntraID/azure_ad/get_user_authentication_methods.py
MicrosoftEntraID/manifest.json
MicrosoftEntraID/tests/test_actions.py

- Change the type of result to dict due to validation function that support just dict type in automation sdk

Change the result type

---

Azure/CHANGELOG.md
Azure/connectors/azure_eventhub.py
Azure/manifest.json

https://github.com/SekoiaLab/integration/issues/232

Azure EventHub - fix epoch error

---

CrowdStrike/CHANGELOG.md
CrowdStrike/aws/sqs.py
CrowdStrike/manifest.json
CrowdStrike/tests/aws/test_sqs.py

- Main issue : [Issue](https://github.com/orgs/SekoiaLab/projects/90/views/2?pane=issue&itemId=81560665)

Set MessageVisibility to one minute

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/alerts.py
Sekoia.io/tests/ic_oc_triggers/test_alerts.py
Sekoia.io/trigger_sekoiaio_alert_comment_created.json

Closes [191](https://github.com/SekoiaLab/integration/issues/191)

Fix: Sekoia add comment info to result ( 191 ) 

---

Google/CHANGELOG.md
Google/connector_google_reports.json
Google/google_module/google_reports.py
Google/manifest.json
Google/trigger_google_reports.json

Related ticket : [Ticket](https://github.com/SekoiaLab/integration/issues/256)

Add vault service

---

HarfangLab/CHANGELOG.md
HarfangLab/action_harfanglab_download_file_from_endpoint.json
HarfangLab/harfanglab/download_file_from_endpoint.py
HarfangLab/harfanglab/job_executor.py
HarfangLab/harfanglab/models.py
HarfangLab/main.py
HarfangLab/manifest.json
HarfangLab/tests/test_download_file_from_endpoint.py

Add the `action_harfanglab_download_file_from_endpoint` action.
Rely on the `downloadFile` job action.

Harfanglab download file from endpoint action

---

Google/CHANGELOG.md
Google/connector_google_reports.json
Google/manifest.json
Google/trigger_google_reports.json

Add some services to config file, ( We support them in the connector but we didn't mention them in config files )
[Issue](https://github.com/SekoiaLab/integration/issues/256)

Add some other services

---

Sekoia.io/CHANGELOG.md
Sekoia.io/action_trigger_an_action_on_the_alert_workflow.json
Sekoia.io/main.py
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/operation_center/__init__.py
Sekoia.io/sekoiaio/operation_center/update_alert_status.py
Sekoia.io/tests/operation_center_action/test_update_alert_status.py

[Parent Task](https://github.com/SekoiaLab/platform/issues/60784)

chore: Use status title instead of uuid when changing alert status

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/connector.py

Change the way to shut down the connector to bypass a little issue in the sdk.

Office365: change the way to shutdown the connector

---

Google/CHANGELOG.md
Google/connector_google_reports.json
Google/manifest.json
Google/trigger_google_reports.json

[improvement ticket ](https://github.com/SekoiaLab/integration/issues/243)

Add chromeOS service

---

MicrosoftDefender/action_add_comment_to_alert.json
MicrosoftDefender/action_cancel_machine_action.json
MicrosoftDefender/action_get_machine_action_info.json
MicrosoftDefender/action_isolate_machine.json
MicrosoftDefender/action_restrict_code_execution.json
MicrosoftDefender/action_scan_machine.json
MicrosoftDefender/action_unisolate_machine.json
MicrosoftDefender/action_unrestrict_code_execution.json
MicrosoftDefender/action_update_alert.json
MicrosoftDefender/manifest.json

declare the fields of the result in order to help the autocompletion when creating a playbook.

MicrosoftDefender: declare properties in the result

---

Azure/CHANGELOG.md
Azure/connector_azure_eventhub.json
Azure/connectors/azure_eventhub.py
Azure/dev.py
Azure/manifest.json
Azure/tests/connector/test_azure_eventhub.py
Azure/trigger_azure_eventhub.json

Closes [261](https://github.com/SekoiaLab/integration/issues/261)

Fix: AzureEventHub epoch issue (261)

---

Sophos/CHANGELOG.md
Sophos/connector_sophos_xdr_query.json
Sophos/manifest.json
Sophos/sophos_module/client/__init__.py
Sophos/trigger_sophos_xdr_query.json

- Add the ratelimit per day
- Increase the frequency to 5 minutes for the XDR connector

Sophos: add ratelimit per day

---

PaloAltoCortexXDR/CHANGELOG.md
PaloAltoCortexXDR/cortex_module/cortex_edr_connector.py
PaloAltoCortexXDR/manifest.json
PaloAltoCortexXDR/tests/test_cortex_edr.py

- Fix the way to handle the responses
- Handle HTTP errors
- Stop the connector when credentials or permissions are invalids

PaloAltoCortexXDR: change the way to handle responses

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/manifest.json

Override the stop method due to an issue in the sdk (fix in progress)

AWS: fix stop method

---

Sekoia.io/CHANGELOG.md
Sekoia.io/action_creates_a_new_asset_v2.json
Sekoia.io/action_deletes_an_asset_v2.json
Sekoia.io/action_list_assets_v2.json
Sekoia.io/action_returns_an_asset.json
Sekoia.io/action_returns_an_asset_v2.json
Sekoia.io/main.py
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/operation_center/__init__.py
Sekoia.io/sekoiaio/operation_center/get_asset.py
Sekoia.io/tests/ic_oc_triggers/test_alerts.py
Sekoia.io/tests/operation_center_action/test_get_asset.py

This is still a WIP, files will be changed not just renamed afterwards after validating validity of changes

chore: move from using asset management V1 endpoints to V2

---

SentinelOne/CHANGELOG.md
SentinelOne/action_create_iocs.json
SentinelOne/manifest.json
SentinelOne/sentinelone_module/iocs/create_iocs.py
SentinelOne/tests/iocs/test_create_iocs.py

- Fix the result problem ( Change the result to dict)

Fix result problem in sentinelOne action

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/singularity/client.py
SentinelOne/sentinelone_module/singularity/connectors.py

Convert the argument to int as the query only accepts Long

SentinelOne: fix the type for the start date time argument

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/tests/triggers/test_consumer.py

Set the hostname and the api token as required in the module configuration.

SentinelOne: fix module configuration

---

Azure/CHANGELOG.md
Azure/connectors/azure_eventhub.py
Azure/manifest.json
Azure/tests/connector/test_azure_eventhub.py

related issue : [issue](https://github.com/SekoiaLab/integration/issues/286)

Add non-json formats to eventhub connector

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/checkpoint.py
Office365/tests/management_api/test_checkpoint.py

Constraint the offset, from the checkpoint, to be always in the last 7 days.

Office365: fix checkpoint

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/connector.py
Office365/poetry.lock
Office365/pyproject.toml

- check if the HTTP client session is defined and not closed

Office365: fix shutdown

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json

Update sekoia module description

Update sekoia module description

---

Sekoia.io/CHANGELOG.md
Sekoia.io/action_trigger_status_update_on_alert.json
Sekoia.io/main.py
Sekoia.io/manifest.json

There was a typo in the docker parameters, preventing the action from being usable.

fix(sekoia.io): docker parameters of update status action

---

Google/CHANGELOG.md
Google/connector_google_reports.json
Google/manifest.json
Google/trigger_google_reports.json

Main Issue : [Issue](https://github.com/SekoiaLab/integration/issues/391#event-16191155665)

change the connector name

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/alerts.py
Sekoia.io/tests/ic_oc_triggers/test_alerts.py
Sekoia.io/trigger_sekoiaio_alert_comment_created.json
Sekoia.io/trigger_sekoiaio_alert_created.json
Sekoia.io/trigger_sekoiaio_alert_status_changed.json
Sekoia.io/trigger_sekoiaio_alert_updated.json
Sekoia.io/trigger_sekoiaio_securityalert.json

Add support for list in rule filter for alert trigger, remove support for rule uuid, as it's must not be used to avoid conflict between rule uuid and rule instance uuid

support list in alert trigger

---

BeyondTrust/CHANGELOG.md
BeyondTrust/beyondtrust_modules/connector_pra_platform.py
BeyondTrust/connector_beyondtrust_pra.json
BeyondTrust/manifest.json
BeyondTrust/poetry.lock
BeyondTrust/pyproject.toml
BeyondTrust/tests/test_connector_pra_platform.py

- Change default batch frequency
- Use cache for session ids

Improve BeyondTrust connector

---

SesameIT/manifest.json

SesameIT: change the name

---

Stormshield/CHANGELOG.md
Stormshield/action_stormshield_deisolate_agent.json
Stormshield/action_stormshield_isolate_agent.json
Stormshield/action_stormshield_quarantine_file.json
Stormshield/action_stormshield_restore_quarantine_file.json
Stormshield/action_stormshield_terminate_process.json
Stormshield/action_stormshield_wait_task.json
Stormshield/manifest.json
Stormshield/stormshield_module/base.py
Stormshield/stormshield_module/wait_task.py

Changes in order that the actions work correctly.
:warning: ~~Please don't merge this PR on our own. Thanks.~~

Stormshield: fix actions

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/connectors/s3/__init__.py
AWS/connectors/s3/trigger_s3_flowlogs.py
AWS/connectors/s3/trigger_s3_flowlogs_parquet.py
AWS/connectors/s3/trigger_s3_ocsf_parquet.py
AWS/connectors/trigger_sqs_messages.py
AWS/main.py
AWS/manifest.json
AWS/tests/connectors/s3/test_abstract_aws_s3_queued_connector.py
AWS/tests/connectors/test_trigger_sqs_messages.py

Closes [465](https://github.com/SekoiaLab/integration/issues/465)

Fix: AWS Connector Memory Leak Issue (465)

---

SentinelOne/CHANGELOG.md
SentinelOne/CONFIGURE.md
SentinelOne/action_update_threat_incident.json
SentinelOne/manifest.json
SentinelOne/tests/threats/test_update_threat_incident.py

Main Issue : [Issue](https://github.com/SekoiaLab/integration/issues/456)

fix uppercase problem

---

Google/CHANGELOG.md
Google/connector_google_reports.json
Google/manifest.json
Google/trigger_google_reports.json

Main Issue : [Issue](https://github.com/SekoiaLab/integration/issues/243)

Change timedelta default value for all services

---

PaloAltoCortexXDR/CHANGELOG.md
PaloAltoCortexXDR/cortex_module/actions/action_xql_query.py
PaloAltoCortexXDR/manifest.json
PaloAltoCortexXDR/tests/actions/test_action_xql_query.py

Small typo in the endpoint name

Fix(Typo) : Fix small typo on endpoint name

---

HarfangLab/harfanglab/asset_connector/device_assets.py
HarfangLab/tests/asset_connector/test_device_assets.py

Fix checkpoint to send all asset for in the first run

Harfanglab: fix checkpoint

---

HarfangLab/manifest.json

Add this parameter to our manifest

Harfanglab: Add parameter to manifest

---

PaloAltoCortexXDR/CHANGELOG.md
PaloAltoCortexXDR/cortex_module/cortex_edr_connector.py
PaloAltoCortexXDR/manifest.json
PaloAltoCortexXDR/tests/test_cortex_edr.py

some alert are not collected at the moment, with this fix we should collect all the alert: https://docs-cortex.paloaltonetworks.com/r/Cortex-XDR-REST-API/Get-all-Alerts

fix paloalto connector
