.github/workflows/build-modules.yml

Execute job only if matrix is not empty to avoid failure on merge
See https://github.com/SEKOIA-IO/automation-library/actions/runs/4992718625

fix: Execute job only if matrix is not empty

---

AzureActiveDirectory/action_disable_user.json
AzureActiveDirectory/action_enable_user.json
AzureActiveDirectory/action_get_signins.json
AzureActiveDirectory/action_get_user.json
AzureActiveDirectory/action_get_user_authentication_methods.json
CrowdStrike Telemetry/manifest.json

* In `CrowdStrike` module add a slug and remove the docker parameter
* The slug is used to push the images in the docker registry
* In `AzureActiveDirectory ` , in the actions replace `slug` by `docker_parameters`.
* SymphonyAPI is expecting a `docker_parameters` attribute when an action is created/updated 
* Later we may change the sync library script to convert `slug` to `docker_parameters` in actions

fix: Fixes docker related attributes in manifests

---

CrowdStrike/CHANGELOG.md
CrowdStrike/aws/sqs.py
CrowdStrike/manifest.json
CrowdStrike/tests/aws/test_sqs.py
CrowdStrike/trigger_crowdstrike_telemetry_events.json

This PR introduces queue_url, an optional trigger configuration parameter.
The user can specify the `queue_url` to hardcode the AWS SQL Url to limit the required permissions on the AWS Tenant.

Introduce an optional parameter to specify the SQS url

---

CrowdStrike/CHANGELOG.md
CrowdStrike/aws/sqs.py
CrowdStrike/crowdstrike_telemetry/pull_telemetry_events.py
CrowdStrike/manifest.json
CrowdStrike/tests/crowdstrike_telemetry/test_crowdstrike.py

This PR fixes the queue_url declaration in the CrowdStrike module.

declare queue_url as a connector parameter in Crowdstrike module

---

CertificateTransparency/CHANGELOG.md
CertificateTransparency/certificatetransparency/triggers/certificate_updated.py
CertificateTransparency/manifest.json
CertificateTransparency/poetry.lock
CertificateTransparency/pyproject.toml

Reimplement Levenshtein distance so that we can remove the dependeyc from python-Levenshtein in CertificateTransparency This library's licence GPLv2 is not compatible with the licence under which CertificateTransparency is distributed

Remove python-Levenshtein dependency

---

VadeSecure/tests/test_m365_events_trigger.py
VadeSecure/vadesecure_modules/trigger_m365_events.py

fix `example.host.net/` instead of `example.host.net` willl construct an url containing two slashes `example.host.net//api/path`

fix(vadesecure/m365): Build remote URL using `urljoin` to prevent bad format

---

Okta/CHANGELOG.md
Okta/manifest.json
Okta/okta_modules/system_log_trigger.py

Add a try-catch around the generator from `__fetch_next_events` to ensure to save the most recent date seen in the context when an exception is raised when getting events from Okta.

Okta: ensure we save the progression 

---

Netskope/manifest.json
Netskope/netskope_modules/connector_pull_events_v2.py
Netskope/netskope_modules/metrics.py
Netskope/tests/test_pull_events_v2_connector.py

Improve the observability of the Netskope connector:
- Harmonize the namespace of the metrics 
- Remove metrics exporter in connectors. The parent class now defines an exporter.
- add a metric to observe the lag

Netskope: improve observability

---

Sekoia.io/manifest.json
Sekoia.io/poetry.lock
Sekoia.io/pyproject.toml
Sekoia.io/sekoiaio/triggers/intelligence.py
Sekoia.io/tests/triggers/test_intelligence.py

In the current implementation the trigger never sends a critical log to the api, so the trigger is never stopped.
It will start over and over again.
With the changes we made, we:
* send a `critical` error if needed
* Wait until the pod is killed
This PR also removes code that is already implemented in the SDK side:
* Method to exit
* Stop event
* Hooking on signals

fix: Small fix in Sekoia.io feed trigger

---

Trellix/CHANGELOG.md
Trellix/manifest.json
Trellix/tests/trellix/test_connector.py
Trellix/trellix/connector.py

Fix the configuration of the connector as the manifest files indicates that the configuration should be in the connector configuration while the code indicates that the configuration should be in the module configuration.

Trellix: fix the configuration

---

CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
CrowdStrikeFalcon/manifest.json

This connector is not forwarding events very often, so we can increase the time to wait without events before restarting the pod.

feat(CrowdStrikeFalcon): Increase time to wait without events

---

Darktrace/CHANGELOG.md
Darktrace/darktrace_modules/threat_visualizer_log_trigger.py
Darktrace/manifest.json
Darktrace/trigger_threat_visualizer_log.json

Add an option to not verify the server certificate when requesting over a TLS connection

Darktrace: Allow unverify connections

---

Sekoia.io/action_get_event_field_common_values.json
Sekoia.io/action_get_events.json
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/operation_center/base_get_event.py
Sekoia.io/sekoiaio/operation_center/get_event_field_common_values.py
Sekoia.io/sekoiaio/operation_center/get_events.py
Sekoia.io/tests/operation_center/test_get_events.py

Add an optional limit parameter for actions querying events.

feat(Sekoia.io): Add limit parameter to get events action

---

Sekoia.io/manifest.json
Sekoia.io/sekoiaio/operation_center/get_events.py
Sekoia.io/tests/operation_center/test_get_events.py

* When the user specified a limit the `total` value must be ignored if bigger than the limit.
* Fix pagination that is not working for the last page because `offset` has already been incremented with `limit` at the end of the previous loop
* If total is bigger than 5 000 then the current code will cause multiple iterations returning nothing because a search job is limited to 5 000 results.
A log has also been added in case we exit early and the number of results doesn't match the total

fix(Sekoia.io): Fix limit param and pagination of results

---

Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/base.py
Sekoia.io/tests/triggers/test_base.py

* Add reconnect option so the socket can connect again on error
* Don't sleep on error since we may lose events
* On stop properly close the socket
* On close reset the socket state so the next `run_forever` call will start from a clean state
* Add debug logs on ping and pong
* Will allow to check if the trigger is still running properly or not
*  Remove `_must_stop` that is redundant with the `_stop_event` attribute

fix(Sekoia.io): Websockets

---

Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/base.py

Prevent error `RuntimeError: threads can only be started once` from happening

fix(Sekoia.io): Do not start thread if still alive

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/manifest.json

Change the `time.sleep` to only wait when no events were forwarded.

AWS: Connectors performance

---

MicrosoftActiveDirectory/microsoft_ad/base.py
MicrosoftActiveDirectory/microsoft_ad/user.py
MicrosoftActiveDirectory/tests/test_user.py

- Improve the way to disable and enable account by getting the real userAccountControl. (We used just 514 and 512 numbers)
- Add an Exception if there's no permission to do some actions

Get the real userAccountControl

---

Proofpoint/CHANGELOG.md
Proofpoint/manifest.json
Proofpoint/proofpoint_modules/helpers.py
Proofpoint/tests/test_helpers.py

Consider that user can provide naive-offset datetime as input

Proofpoint: change the way to handle user provided datetime

---

Netskope/CHANGELOG.md
Netskope/manifest.json
Netskope/netskope_modules/connector_pull_events_v2.py
Netskope/netskope_modules/models.py
Netskope/tests/test_pull_events_v2_connector.py

Set the module configuration property `base_url` as nullable (but required) and update the Netskope Events connector to check if this property is defined or not.

Netskope: set base_url property as nullable

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/pyproject.toml
Sekoia.io/sekoiaio/intelligence_center/actions.py
Sekoia.io/sekoiaio/triggers/alerts.py
Sekoia.io/sekoiaio/triggers/base.py
Sekoia.io/sekoiaio/triggers/intelligence.py
Sekoia.io/tests/triggers/conftest.py
Sekoia.io/tests/triggers/samples.py
Sekoia.io/tests/triggers/test_alerts.py
Sekoia.io/tests/triggers/test_base.py

Update the Sekoia.io module to handle “v2 notifications”. This required to change a few things in the existing codebase.
Changes:
- In `_SEKOIANotificationBaseTrigger`, move away from the `handle_${event_type}` and only rely on a `handle_event` function that should be in charge of filtering the collected event. This way, the `SecurityAlertsTrigger` can handle alert notifications (`alert:created`, `alert:updated`, and `alert-comment:created` kind of events).
- Update `AlertCommentCreatedTrigger` to only handle changes about alert status changed (status changes are now in `alert:updated` events).
- Add a new `on_open()` callback to ask `liveapi` to send v2 notifications.
- Update test samples to be v2 notifications.

Sekoia.io: Read v2 notifications from `liveapi`

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/alerts.py
Sekoia.io/tests/triggers/test_alerts.py

If an error is raised when trying to fetch an alert from the Alert API (after 10 retries), then, log explicitly the error that was raised.

Sekoia.io: Explictly log all Alert API exceptions

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/trigger_sekoiaio_alert_comment_created.json
Sekoia.io/trigger_sekoiaio_alert_created.json
Sekoia.io/trigger_sekoiaio_alert_status_changed.json
Sekoia.io/trigger_sekoiaio_alert_updated.json
Sekoia.io/trigger_sekoiaio_securityalert.json

Update the description so the user rely on the rule name instead of the uuid.
Usually the user provides the rule definition uuid instead of the rule instance uuid, making the trigger not handle any alerts.
By using the name there will be no possible confusion.

feat(Sekoia.io): Update rule filter description

---

AWS/CHANGELOG.md
AWS/aws_helpers/sqs_wrapper.py
AWS/manifest.json
AWS/tests/aws_helpers/test_sqs_wrapper.py

In the SQS wrapper, set the [MessageVisibility](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) to one minute.

AWS: Set MessageVisibilty to one minute

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/intelligence_center/actions.py
Sekoia.io/tests/test_post_bundle.py

Empty bundles are rejected by the Intelligence Center. This PR avoids to send them.

fix(Sekoia.io): Do not push empty bundles to the IC

---

CrowdStrikeFalcon/CHANGELOG.md
CrowdStrikeFalcon/crowdstrike_falcon/client/retry.py
CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
CrowdStrikeFalcon/crowdstrike_falcon/logging.py
CrowdStrikeFalcon/manifest.json
CrowdStrikeFalcon/poetry.lock
CrowdStrikeFalcon/pyproject.toml
CrowdStrikeFalcon/tests/test_event_stream_trigger.py

After a ratelimit on the authentication, the connector stopped collecting the events because `f_stop` was set at the end of the `run` method.
Changes applied:
- change the way to manage thread:
- change the way to handle graceful shutdown
- outsource the reading of the events queue in a dedicated and stoppable thread
- remove the expression that set `f_stop` at the end of the `run` method
- Add a timer to sleep 1 minute if the connector faces a ratelimit.

CrowdStrikeFalcon: Fix stop of the collect when facing ratelimit

---

Salesforce/CHANGELOG.md
Salesforce/manifest.json
Salesforce/salesforce/connector.py
Salesforce/trigger_salesforce_events.json

Pause the connector (by default, during 10 minutes, as the Salesforce API generate hourly log files) when no records were returned from the previous batch.

Salesforce: pause the connector when no records were returned

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/manifest.json

AWS timestamps are in milliseconds. Convert them into seconds to compute the delay.

AWS: fix the way to compute the lag

---

AWS/CHANGELOG.md
AWS/connectors/s3/trigger_s3_records.py
AWS/manifest.json
AWS/tests/connectors/s3/test_trigger_s3_records.py

Proposal to add custom filtering for ec2 events instead of the default one.
For detection purpose we need most of the Describe* events from ec2.
We defined an unsupported list of events we do not need instead and are quite huge currently in terms of EPS.

feat(AWS): allowing ec2 events with custom unsupported events

---

ExtraHop/CHANGELOG.md
ExtraHop/extrahop/models.py
ExtraHop/extrahop/reveal_360_trigger.py
ExtraHop/manifest.json
ExtraHop/tests/test_connector.py

Use `posixpath.join` to compute the url of the endpoint, in order to avoid issue when the customer set the base_url with an ending slash.

ExtraHop: change the way to compute the url of the endpoint

---

Lacework/lacework_module/base.py
Lacework/lacework_module/client/__init__.py
Lacework/lacework_module/client/auth.py
Lacework/lacework_module/lacework_connector.py
Lacework/manifest.json
Lacework/tests/client/test_auth.py
Lacework/tests/client/test_client.py
Lacework/tests/test_lacework_connector.py

Update the module configuration to match the lacework terminology.
For an APIKey, we get the KeyId, the secret and the account (i.e, the base url of the Lacework tenant). In order to avoid misconfiguration from users, we replace the old parameters names, in the module configuration with these terms.

Lacework: Update the module configuration

---

CrowdStrikeFalcon/CHANGELOG.md
CrowdStrikeFalcon/crowdstrike_falcon/client/__init__.py
CrowdStrikeFalcon/crowdstrike_falcon/custom_iocs.py
CrowdStrikeFalcon/manifest.json
CrowdStrikeFalcon/tests/client/test_client.py
CrowdStrikeFalcon/tests/test_actions_iocs.py

- Add intermediate steps when deleting indicators to avoid one big calls at the end that may exceed some HTTP limitations
- Change the way to paginate the responses from CrowdStrike. The endpoints don't accept that the `offset` parameter exceed 10000. Instead, CrowdStrike recommends using the `after` parameters.
- Fix the condition that finalize the pagination (to avoid infinite loops).

CrowdStrike: Improve the way to delete indicators

---

Cybereason/CHANGELOG.md
Cybereason/cybereason_modules/client/auth.py
Cybereason/cybereason_modules/connector_pull_events.py
Cybereason/manifest.json
Fastly/CHANGELOG.md
Fastly/fastly/connector_fastly_waf_base.py
Fastly/manifest.json
Lacework/CHANGELOG.md
Lacework/lacework_module/lacework_connector.py
Lacework/manifest.json
Sophos/CHANGELOG.md
Sophos/manifest.json
Sophos/sophos_module/trigger_sophos_edr_events.py

Handle the computation of the events lag when no events were fetched from the API

Fix the way to compute the lag

---

Nybble/CHANGELOG.md
Nybble/manifest.json
Nybble/nybble_modules/create_alert.py
Nybble/tests/test_create_alerts.py

sometimes, events are not containing all fields present in the rule which has triggered the alert.
Fixing the code to handle this.

Nybble / fixing optional field in events but listed in rule

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/checkpoint.py
Office365/tests/management_api/test_checkpoint.py

The checkpoint track internally (cursor) the date of the last message seen. However, this cursor was not updated when saving a new date. 
This PR fixes this behavior.

Office365: fix the checkpoint

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/connector.py

Fix the dates to use when pulling new contents.
We have to use the dates from the date ranges, not the ones from the whole period of times to fetch.

Office365: fix dates to use for pulling

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/connector.py

The close method, from the Office365 Client, is async. So, we have to await it inside an async method.

Office365: change how to close Office365 client

---

Bitsight/CHANGELOG.md
Bitsight/connectors/pull_findings_trigger.py
Bitsight/manifest.json
Darktrace/CHANGELOG.md
Darktrace/darktrace_modules/threat_visualizer_log_trigger.py
Darktrace/manifest.json
ExtraHop/CHANGELOG.md
ExtraHop/extrahop/reveal_360_trigger.py
ExtraHop/manifest.json
Office365/tests/management_api/test_helpers.py
PaloAltoCortexXDR/CHANGELOG.md
PaloAltoCortexXDR/cortex_module/cortex_edr_connector.py
PaloAltoCortexXDR/manifest.json

- For Darktrace and BitSight, handle the case when no events are collected to compute the event lags.
- For ExtraHop and PaloAlto Cortex XDR, change the precision of the timestamps.

Connectors: fix the way to compute lag

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/manifest.json

- Change the way to report the lag, when no events were collected
- Refactor the way to pause the connector

AWS: change the way to compute the events lag

---

CatoNetwork/CHANGELOG.md
CatoNetwork/manifest.json

- allows 4 or 5 digits for the accountID

CatoNetwork: extends the length of the accountID to 5 digits

---

CrowdStrike/CHANGELOG.md
CrowdStrike/crowdstrike_telemetry/metrics.py
CrowdStrike/crowdstrike_telemetry/pull_telemetry_events.py
CrowdStrike/manifest.json
CrowdStrike/tests/crowdstrike_telemetry/test_crowdstrike.py

Add a filter on specific Crowdstrike Falcon logs:
- event_simpleName not defined
- event_simpleName in :
"SensorHeartbeat",
"ConfigStateUpdate",
"ErrorEvent",
"FalconServiceStatus",
"CurrentSystemTags",
"BillingInfo",
"ChannelActive",
"IdpDcPerfReport",
"ProvisioningChannelVersionRequired",
"ChannelVersionRequired",
"SensorSelfDiagnosticTelemetry",
"SystemCapacity",
"MobilePowerStats",
"DeliverRulesEngineResultsToCloud",
"NeighborListIP4",
"NeighborListIP6",
"AgentConnect",
"AgentOnline",
"ResourceUtilization",

Filters for Crowdstrike falcon telemetry

---

Sophos/CHANGELOG.md
Sophos/manifest.json
Sophos/sophos_module/trigger_sophos_xdr_query.py

The API return a 201 when creating a new query. Change the expected status code to only logs on errors.

Sophos: fix expected status code

---

Netskope/CHANGELOG.md
Netskope/manifest.json
Netskope/netskope_modules/connector_pull_events_v2.py

The metric was only updated when new events were fetched. Fix the way to compute the lag to consider when no events were collected.

Netskope: fix the way to compute the event lag

---

Trellix/CHANGELOG.md
Trellix/connectors/trellix_edr_connector.py
Trellix/connectors/trellix_epo_connector.py
Trellix/manifest.json

Use the logger of the connector to push messages to the interface.

Trellix: use connector's logger

---

CrowdStrikeFalcon/CHANGELOG.md
CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
CrowdStrikeFalcon/manifest.json
CrowdStrikeFalcon/tests/test_event_stream_trigger.py

try to have the content of the response when the url failed

CrowdStrike: change the way to log errors when refreshing datafeed

---

Google/CHANGELOG.md
Google/google_module/google_reports.py
Google/manifest.json

When restarting, the connector starts to collect events from the `most recent date seen` to the `most resent date seen` + the interval (the `frequency`) to request. This behavior drives having a slow catch back of events if the `most recent date seen` is days ago.
To speed up the catch back, we set the end of the period to call to the upper bound (i.e, now - the temporal shift to collect the logs). In that way, the first call will retrieve all events from the `most recent date seen` to the moment the connector restarted.
PS: I also remove the pause in the connector as the TimeStepper class already compute one.

Google: Change the end of the period to call when restarting the connector

---

Trellix/CHANGELOG.md
Trellix/client/token_refresher.py
Trellix/manifest.json
Trellix/tests/client/test_token_refresher.py

- Raise exceptions on authentication when facing 4xx status code
- Fix the way to compute the authentication url

Trellix: Fix the authentication url

---

CrowdStrikeFalcon/CHANGELOG.md
CrowdStrikeFalcon/crowdstrike_falcon/event_stream_trigger.py
CrowdStrikeFalcon/crowdstrike_falcon/helpers.py
CrowdStrikeFalcon/manifest.json
CrowdStrikeFalcon/tests/test_helpers.py

The connector read a long pulling request to get the events. To keep this connection alive, we have to call a URL on a regular interval.
Until now, the connector uses the interval provided by the API. Now, we add a safety margin to this interval to avoid calling the URL outside the time range.

CrowdStrikeFalcon: change the way to compute the refresh interval

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/triggers/alerts.py
Sekoia.io/sekoiaio/triggers/base.py
Sekoia.io/sekoiaio/triggers/intelligence.py
Sekoia.io/tests/ic_oc_triggers/test_base.py
Sekoia.io/tests/ic_oc_triggers/test_intelligence.py

* Handle cases where the base URL from the config has the `/api` or not.
* Harmonize all the triggers
* `/me` and `/v2/inthreat` were expecting `/api` to be in the base url (or that the base url is `https://api.sekoia.io`)
*  `/v1/sic/alerts` was not expecting `/api` to be in the URL
The fix should also work with `https://api.sekoia.io` because `https://api.sekoia.io/api` also works.

fix(Sekoia.io): Fixes potential errors in URLs

---

Azure/CHANGELOG.md
Azure/connectors/azure_eventhub.py
Azure/manifest.json

Reset the event lag when no message was received after several seconds.

Azure: reset event lag when no message was received

---

Trellix/CHANGELOG.md
Trellix/client/http_client.py
Trellix/client/retry.py
Trellix/client/token_refresher.py
Trellix/manifest.json
Trellix/poetry.lock
Trellix/pyproject.toml
Trellix/tests/client/test_http_client.py
Trellix/tests/client/test_retry.py

- add a safety margin when refreshing the token
- Add retries on HTTP errors
- Handle 429 HTTP responses

Trellix: add retries on HTTP errors

---

ThinkstCanary/CHANGELOG.md
ThinkstCanary/manifest.json
ThinkstCanary/thinkst_canary_modules/connector_thinkst_canary_alerts.py

and fix the way to compute the events lag (specially when no events were forwarded)

ThinkstCanary: Set version number to 1.0.0

---

Sekoia.io/CHANGELOG.md
Sekoia.io/manifest.json

To achieve internal/automatic configuration of the Sekoia.io modules, they have to *not* require a configuration from the user.
Their configuration elements have been removed.
This configuration will be created and linked to the module in Symphony API but won't be accessible to the user.
Only the `secrets` field has been kept in order to encrypt the relevant field when it will be automatically created.
Parent task: [#58166](https://github.com/SekoiaLab/platform/issues/58166)

Remove need for a configuration for Sekoia modules

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/logs/connector.py
SentinelOne/sentinelone_module/logs/helpers.py
SentinelOne/tests/logs/test_connector.py
SentinelOne/tests/logs/test_helpers.py

Currently, the connector doesn't use the most recent date seen to query new events.
So we always collect the same events
The context is used by two threads for the collect of events. However, it wasn't thread-safe and each thread could erase the progression of the other thread
Externalize the method to add test and simplify its maintenance

SentinelOne: Fix the usage of the cursor in the connector

---

Sekoia.io/CHANGELOG.md
Sekoia.io/action_get_event_field_common_values.json
Sekoia.io/action_get_events.json
Sekoia.io/manifest.json
Sekoia.io/sekoiaio/operation_center/base_get_event.py
Sekoia.io/sekoiaio/operation_center/get_event_field_common_values.py
Sekoia.io/sekoiaio/operation_center/get_events.py
Sekoia.io/tests/operation_center_action/test_get_events.py

A default limit was not applied on the first query when it was not provided in the arguments. 
Also the max in the code was set to `1 000` and in the manifest it was `100`. I updated the code to reflect the manifest, but we can pass it to `1 000` if you feel `100` is too low
This PR also raise the default limit to `100`.

feat(Sekoia.io): Enforce default and limit from manifests

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/poetry.lock
SentinelOne/pyproject.toml
SentinelOne/sentinelone_module/logs/connector.py
SentinelOne/sentinelone_module/logs/helpers.py
SentinelOne/tests/logs/test_connector.py
SentinelOne/tests/logs/test_helpers.py

Filter the events in order to discard already collected ones. We use a LRU cache to save temporary the identifier of the last colllected events.

SentinelOne: filter collected events

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/logs/connector.py
SentinelOne/tests/conftest.py
SentinelOne/tests/logs/test_connector.py

- Handle threats as a dict (and not an object with properties).
- declare `batch_duration` as we use it to compute the pause.

SentinelOne: fix connector

---

AWS/CHANGELOG.md
AWS/connectors/__init__.py
AWS/connectors/metrics.py
AWS/manifest.json
Azure/CHANGELOG.md
Azure/connectors/azure_eventhub.py
Azure/connectors/metrics.py
Azure/manifest.json

Use a histogram to monitor the age of SQS notifications for AWS and the age of messages for Azure Event Hub

AWS/Azure: change the way to monitor the age of messages

---

VadeSecure/CHANGELOG.md
VadeSecure/manifest.json
VadeSecure/vadesecure_modules/trigger_m365_events.py

When the trigger fails to authenticate against the Vade API, log the message as critical in order to stop the trigger after 5 fails

VadeSecure: Stop the trigger when failing to authenticate

---

VadeCloud/CHANGELOG.md
VadeCloud/manifest.json
VadeCloud/vadecloud_modules/trigger_vade_cloud_logs.py

Log as critical, any authentication error. This will stop the connector after 5 failures

VadeCloud: Stop connector on authentication errors

---

MicrosoftActiveDirectory/action_search.json

Add the identifier is already used, it prevents the deployment of the action. Fix it

MicrosoftActiveDirectory: fix the identifier of the action

---

Tehtris/CHANGELOG.md
Tehtris/manifest.json
Tehtris/tehtris_modules/trigger_tehtris_events.py
Tehtris/tests/test_tehtris_event_trigger.py

The `uid` is not unique and discard too many events. Use `id` instead.

Tehtris: change the fitler for duplicated events

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/checkpoint.py
Office365/tests/management_api/test_checkpoint.py

Reduce to 7 days the catch back in the past as the API only support 7 days.
```
{"error":{"code":"AF20055","message":"Start time and end time must both be specified (or both omitted) and must be less than or equal to 24 hours apart, with the start time prior to end time and start time no more than 7 days in the past. StartTime:2024-10-05T10:27:13.619091+00:00, EndTime:2024-10-05T10:57:13.619091+00:00"}}
```

Office365: Reduce to 7 days the catch back in the past

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/singularity/client.py
SentinelOne/tests/singularity/test_client.py

The module configuration accepts the hostname of the tenant, not the base url. Fix it.

SentinelOne: fix the way to compute the url of the tenant.

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/singularity/connectors.py

Intercept the Timeout exception that can be raised time to time.
Handle it as a normal event.

SentinelOne: handle Timeout exception

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/singularity/client.py
SentinelOne/sentinelone_module/singularity/connectors.py
SentinelOne/tests/singularity/test_connectors.py

- Reduce the verbosity of the GQL client in the logs
- Fix the pagination in the Singularity connector.

SentinelOne: fix the pagination

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/sentinelone_module/helpers.py
SentinelOne/sentinelone_module/logs/connector.py
SentinelOne/sentinelone_module/logs/helpers.py
SentinelOne/sentinelone_module/singularity/connectors.py
SentinelOne/tests/logs/test_helpers.py
SentinelOne/tests/singularity/conftest.py
SentinelOne/tests/singularity/test_connectors.py
SentinelOne/tests/test_helpers.py

- Convert the start_time into milliseconds (because it's the precision expected by the API)
- Add a cache to discard already collected alerts.

SentinelOne: Fix the start_time

---

Netskope/CHANGELOG.md
Netskope/manifest.json
Netskope/netskope_modules/connector_pull_events_v2.py

https://github.com/SekoiaLab/integration/issues/324

Netskope - fix trigger configuration

---

SentinelOne/CHANGELOG.md
SentinelOne/manifest.json
SentinelOne/pyproject.toml
SentinelOne/sentinelone_module/logs/connector.py
SentinelOne/sentinelone_module/singularity/client.py
SentinelOne/sentinelone_module/singularity/connectors.py
SentinelOne/tests/singularity/test_client.py
SentinelOne/tests/singularity/test_connectors.py
SentinelOne/tests/test_helpers.py

Fixes [351](https://github.com/SekoiaLab/integration/issues/351)

Feature: SentinelOne detailed alert view (351)

---

Office365/CHANGELOG.md
Office365/manifest.json
Office365/office365/management_api/connector.py

Save the end date of each date ranges, computed from the pulling period, in the checkpoint, in order to always progress;
and not wait that the connector caught back the delay to save the end date.

Office365: save end date of date range in the checkpoint

---

Mimecast/CHANGELOG.md
Mimecast/manifest.json
Mimecast/mimecast_modules/connector_mimecast_siem.py
Mimecast/tests/test_mimecast_siem_logs.py

Move the initialization of the authentication in the run method. The resolution of secrets is done just before this method.

Mimecast: Fix Authentication issue

---

AWS/CHANGELOG.md
AWS/connectors/s3/__init__.py
AWS/manifest.json

- Fix typing issue: a list (the list of event IDs) cannot be added to an integer (`results`)
- reset the records list when pushing it

AWS: fix issues when reading S3 notification

---

VadeSecure/CHANGELOG.md
VadeSecure/manifest.json
VadeSecure/tests/test_m365_events_trigger.py
VadeSecure/tests/test_m365_mixin.py
VadeSecure/vadesecure_modules/connector_m365_events.py
VadeSecure/vadesecure_modules/m365_mixin.py
VadeSecure/vadesecure_modules/trigger_m365_events.py

Change the way to handle errors from VadeSecure Errors:
During startup, if we face a 401or 403 errors, the connector is immediately stopped
During collect, if we face a 403 error, the connector is immediately stopped
During collect, if we face a 401 or 500 error, the connector is paused and retry later.

VadeSecure: change the way to handle 401 and 500 HTTP erros

---

VadeCloud/CHANGELOG.md
VadeCloud/manifest.json
VadeCloud/tests/test_vade_cloud_logs_trigger_unitary.py
VadeCloud/vadecloud_modules/trigger_vade_cloud_logs.py

Change the way to handle errors from VadeCloud Errors:
- During startup, if we face a 401, 403 or 400 errors, the connector is immediately stopped
- During collect, if we face a 403 error, the connector is immediately stopped
- During collect, if we face a 401 or 500 error, the connector is paused and retry later.

VadeCloud: Change the way to handle 401 and 500 errors
